name: Enforce Current Year in README

# Trigger once a year (Jan 1), on any README.md change, or manually
on:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    paths:
      - README.md
  workflow_dispatch:

jobs:
  enforce-readme-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow commits via GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and update year
        run: |
          current_year=$(date +'%Y')

          # 1) Try same-line marker: <!-- change year start -->YYYY<!-- change year end -->
          extracted=$(sed -n 's/.*<!-- change year start -->[[:space:]]*\([0-9]\{4\}\)[[:space:]]*<!-- change year end -->.*/\1/p' README.md)

          # 2) Fallback: markers on separate lines
          if [ -z "$extracted" ]; then
            extracted=$(awk '/<!-- change year start -->/{getline; print}' README.md | grep -Eo '[0-9]{4}')
          fi

          echo "Found year between markers: $extracted"
          echo "Current system year:       $current_year"

          if [[ "$extracted" =~ ^[0-9]{4}$ ]] && [[ "$extracted" != "$current_year" ]]; then
            echo "Year differs. Updating to $current_year..."

            # Replace same-line style
            sed -i 's|\(<!-- change year start -->\)[[:space:]]*[0-9]\{4\}\([[:space:]]*<!-- change year end -->\)|\1 '"${current_year}"'\2|' README.md

            # Replace multi-line style
            sed -i '/<!-- change year start -->/{n;s/[0-9]\{4\}/'"$current_year"'/;}' README.md

            echo "YEAR_UPDATED=1" >> $GITHUB_ENV
          else
            echo "No update needed."
            echo "YEAR_UPDATED=0" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.YEAR_UPDATED == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure the official Actions bot identity:
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Recompute for an accurate commit message
          current_year=$(date +'%Y')

          git add README.md
          git commit -m "fix(readme): enforce year $current_year"
          git push
